// HW instructions - https://docs.google.com/document/d/1L2xEpABMBZbciuLVFSsLD6fH5jcR0bPwLt2-wvzKNj0/edit?usp=sharing
pipeline{
    agent any
    stages{
        stage("Cloning..."){
            steps{
                echo "=== Git cloning the repo ==="
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/MaorW/jenkinsHW02.git']]])
                echo "Git repo has been cloned..."
            }
        }
        stage("building..."){
            steps{
                echo "=== Building ==="
                sh 'python3 http_e.py'
            }
        }
        stage("Testing..."){
            steps{
                echo "=== Testing ==="                
                sh 'pytest RestTest.py'
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
           sh 'docker build -t requestFromJenkins .'
        }
    }
}
