// HW instructions - https://docs.google.com/document/d/1L2xEpABMBZbciuLVFSsLD6fH5jcR0bPwLt2-wvzKNj0/edit?usp=sharing
pipeline{
    agent any
    stages{
        stage("Cloning..."){
            steps{
                echo "=== Git cloning the repo ==="
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/MaorW/jenkinsHW01.git']]])
                echo "Git repo has been cloned..."
                echo "Executing main.py file"
                sh "python3 jenkinsHW01/main.py"
            }
        }
        stage("building..."){
            steps{
                echo "=== Building ==="      
                sh 'docker build -t HW/01 jenkinsHW01'          
            }
        }
        // stage("Testing..."){
        //     steps{
        //         echo "=== Testing ==="                
        //     }
        // }
        // stage("deploying..."){
        //     steps{
        //         echo "=== deploying ==="                
        //     }
        // }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
            mail bcc: '', body: "<b>Example</b><br>\n\<br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "learningmw1991@gmail.com";
        }
    }
}
