// HW instructions - https://docs.google.com/document/d/1L2xEpABMBZbciuLVFSsLD6fH5jcR0bPwLt2-wvzKNj0/edit?usp=sharing
pipeline{
    agent any
    stages{
        stage("Cloning..."){
            steps{
                echo "=== Git cloning the repo ==="
                sh 'git clone https://github.com/MaorW/jenkinsHW01.git'
                echo "Git repo has been cloned..."
                echo "Executing main.py file"
                sh "python3 jenkinsHW01/main.py"
            }
        }
        stage("building..."){
            steps{
                echo "=== Building ==="                
            }
        }
        stage("Testing..."){
            steps{
                echo "=== Building ==="                
            }
        }
        stage("deploying..."){
            steps{
                echo "=== deploying ==="                
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
